#pragma once

#include <array>
#include <atomic>
#include <cstddef>
#include <cstdint>
#include <optional>
#include <utility>

// Generated by the Makefile from the untouched exercise implementation. The
// generated copy only exposes the operations and renames its standalone main.
#ifndef SPSC_QUEUE_TESTABLE_INCLUDE
#define SPSC_QUEUE_TESTABLE_INCLUDE "SPSQQueue.testable.inc"
#endif
#include SPSC_QUEUE_TESTABLE_INCLUDE

struct QueueItem {
    std::uint64_t sequence = 0;
    std::uint64_t checksum = 0;
    bool present = true;

    QueueItem() = default;

    explicit QueueItem(std::uint64_t value)
        : sequence(value), checksum(ExpectedChecksum(value)) {
    }

    // Compatibility with the current exercise implementation. This can be
    // removed once try_pop works directly with an ordinary value type.
    QueueItem(std::optional<QueueItem>& value) {
        if (value) {
            *this = *value;
        } else {
            present = false;
        }
    }

    static constexpr std::uint64_t ExpectedChecksum(std::uint64_t value) {
        return (value * 0x9e3779b97f4a7c15ULL) ^ 0xd1b54a32d192ed03ULL;
    }

    bool IsValid() const {
        return present && checksum == ExpectedChecksum(sequence);
    }

};

// The exercise currently compares the extracted value with nullopt. Give the
// test value an unambiguous empty representation without changing the queue.
inline bool operator==(const QueueItem& item, std::nullopt_t) {
    return !item.present;
}
